version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: luxonis
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    container_name: adminer
    ports:
      - '8081:8080'
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/luxonis