version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: luxonis_test_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=luxonis
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data