version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: luxonis
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/luxonis